### PR TITLE
Support Client Certificate, editorconfig and minor cleanup

### LINKED ISSUE #41: Support for Client Certificate
Hello, thanks for a top notch cake extension 👌 .

I have an application that requires client certificate when calling its RESTful API. It looks like this addin does not have support for this scenario at the moment. On the other hand, it shouldn't be that difficult to expose client certificate in `HttpSettings` and then set it the handler's `ClientCertificates`.

Let me know what you think - I'd be more than happy to submit a PR if you think it's a good idea.

Keep up the good work!

### LINKED ISSUE #42: Add editorconfig to repo
Adding an [editorconfig](http://editorconfig.org/) file to the root of the repo helps other develpers follow the coding style of the solution.

### PR DESCRIPTION
**Pull request by pardahlman**
This PR fixes #41 as well as fixes #42 (the latter in order for me to contribute without changing my personal IDE preferences).

To support `netstandard1.6` and `net46`  I had to add compiler directives to the `CakeHttpClientHandler` (described more closely in #41).

Unit tests for the new extension method `AddClientCertificates` are added. However, I coundn't figure out a good test for making sure that the request was posted with client certificates (jsonplaceholder didn't have any endpoints for this). Instead I added a test that verified that the supplied client certificates ended up in the HttpHandler's `ClientCertificate` property. The fact that the alias is a static class and that the http client is created inside it makes it difficult to mock etc - let me know if you can think of a test case that verifies that the client cert is actually sent!

This PR also contains some minor cleanup:
* Removing trailing whiltespaces
* Removing extra linebreak(s)
* Implicit re-throw of exception
* Simplify property group condition in csproj
* Use [throw expression](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#throw-expressions)

Let me know what you think!

### CODE REVIEW

**Comment by louisfischer** [comment]
@pardahlman Thanks for the pull request. I reviewed it and it looks good. The only issue i saw was that the  cake tests project is failing due to the Tests project not referencing WebRequest.

 File Name: Cake.Http.Tests\Unit\CakeHttpClientHandlerTests.cs Line Number: 29 Message: Module 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' should be referenced

**Comment by pardahlman** [comment]
Hi, I noticed that, too. However - I'm not familiar with that checker and have idea why it is failing. The test project references the correct binaries for net46, see this line: https://github.com/cake-contrib/Cake.Http/pull/43/files#diff-84a88f75fcc05ec266482d1797f03f9aR28

```
   <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
     <Reference Include="System.Net.Http" />
     <Reference Include="System.Net.Http" />
     <Reference Include="System.Net.Http.WebRequest" />
   </ItemGroup>
   </ItemGroup>
```

**Comment by pardahlman** [comment]
Hello again @louisfischer - can you shed some light over this checker and why it is failing? I'm wondering if perhaps it can not handle conditional references...?

**Comment by louisfischer** [comment]
@pardahlman It looks like a violation in the CodeInspection on the AppVeyor Build

image

**Comment by pardahlman** [comment]
Thanks @louisfischer 👍

**Pull request merged**
