### PR TITLE
Update cake references

### LINKED ISSUE #74: Support Cake 2.0.0
Cake 2.0.0 was released on 30th November.
Please provide a version supporting this new release.

### PR DESCRIPTION
**Pull request by twenzel**
- Update reference to Cake 2.0, beside 1.0
- Support NET 5
- Support NET 6

Fixes #74

### CODE REVIEW

**Comment by twenzel** [comment]
@louisfischer Could you take a look at it?

**Comment by MattBussing** [comment]
Looks good to me!

**Comment by twenzel** [comment]
@louisfischer Is something missing?

**Comment by jthiesen** [comment]
It's currently not possible to build Cake 2.x builds with Cake.Http references without getting warnings like this:

`The assembly 'Cake.Http, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (1.0.0).
For best compatibility it should target Cake.Core version 2.0.0.`

Would it be possible to merge this PR to fix this?

**Comment by twenzel** [comment]
@louisfischer or @pascalberger are you a maintainer of this repo?

**Comment by twenzel** [comment]
@louisfischer Please can you publish a new release?

**Pull request merged**
